-- db chema definition
DROP SCHEMA IF EXISTS registry;
CREATE SCHEMA registry;

use registry;

CREATE TABLE ops (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    title VARCHAR(100) NOT NULL,
    description TEXT,
    PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE users(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    fullname VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE registers (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id INT UNSIGNED NOT NULL,
    op_id INT UNSIGNED NOT NULL,
    record_time DATE NOT NULL,
    CONSTRAINT user_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT op_id_fk FOREIGN KEY (op_id) REFERENCES ops(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    PRIMARY KEY (id, user_id, op_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


