package registry.hibernate;
// Generated Jul 29, 2013 9:22:08 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Registers generated by hbm2java
 */
@Entity
@Table(name = "registers", catalog = "registry")
public class Registers implements java.io.Serializable {

    private RegistersId id;
    private Users users;
    private Ops ops;
    private Date recordTime;

    public Registers() {
    }

    public Registers(RegistersId id, Users users, Ops ops) {
        this.id = id;
        this.users = users;
        this.ops = ops;
    }

    public Registers(RegistersId id, Users users, Ops ops, Date recordTime) {
        this.id = id;
        this.users = users;
        this.ops = ops;
        this.recordTime = recordTime;
    }

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "id", column =
                @Column(name = "id", nullable = false)),
        @AttributeOverride(name = "userId", column =
                @Column(name = "user_id", nullable = false)),
        @AttributeOverride(name = "opId", column =
                @Column(name = "op_id", nullable = false))})
    public RegistersId getId() {
        return this.id;
    }

    public void setId(RegistersId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "op_id", nullable = false, insertable = false, updatable = false)
    public Ops getOps() {
        return this.ops;
    }

    public void setOps(Ops ops) {
        this.ops = ops;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "record_time", length = 19)
    public Date getRecordTime() {
        return this.recordTime;
    }

    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }
}
