package hb.tools.annotation;
// Generated Nov 15, 2012 10:05:05 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Company generated by hbm2java
 */
@Entity
@Table(name = "company", catalog = "lazy")
public class Company implements java.io.Serializable {

    private Integer companyId;
    private String name;
    private Set<Customer> customers = new HashSet<Customer>(0);
    private Set<Supplier> suppliers = new HashSet<Supplier>(0);

    public Company() {
    }

    public Company(String name) {
        this.name = name;
    }

    public Company(String name, Set<Customer> customers, Set<Supplier> suppliers) {
        this.name = name;
        this.customers = customers;
        this.suppliers = suppliers;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "company_id", unique = true, nullable = false)
    public Integer getCompanyId() {
        return this.companyId;
    }

    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    @Column(name = "name", nullable = false, length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(cascade = CascadeType.ALL,
    fetch = FetchType.LAZY,
    mappedBy = "company",
    targetEntity = hb.tools.annotation.Customer.class)
    public Set<Customer> getCustomers() {
        return this.customers;
    }

    public void setCustomers(Set<Customer> customers) {
        this.customers = customers;
    }

    @OneToMany(cascade = CascadeType.ALL,
    fetch = FetchType.LAZY,
    mappedBy = "company",
    targetEntity = hb.tools.annotation.Supplier.class)
    public Set<Supplier> getSuppliers() {
        return this.suppliers;
    }

    public void setSuppliers(Set<Supplier> suppliers) {
        this.suppliers = suppliers;
    }
}
