package enterprise.model.registry;
// Generated Jul 29, 2013 9:22:08 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Op generated by hbm2java
 */
@Entity
@Table(name = "ops", catalog = "registry")
public class Op implements java.io.Serializable {

    private Integer id;
    private String title;
    private String description;
    private Set<Register> registers = new HashSet<Register>(0);

    public Op() {
    }

    public Op(String title) {
        this.title = title;
    }

    public Op(String title, String description, Set<Register> registers) {
        this.title = title;
        this.description = description;
        this.registers = registers;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "title", nullable = false, length = 100)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "description")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "op")
    public Set<Register> getRegisters() {
        return this.registers;
    }

    public void setRegisters(Set<Register> registerses) {
        this.registers = registerses;
    }
}
