package enterprise.model.registry;
// Generated Jul 29, 2013 9:22:08 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Register generated by hbm2java
 */
@Entity
@Table(name = "registers", catalog = "registry")
public class Register implements java.io.Serializable {

    private RegisterId id;
    private User user;
    private Op op;
    private Date recordTime;

    public Register() {
    }

    public Register(RegisterId id, User users, Op ops) {
        this.id = id;
        this.user = users;
        this.op = ops;
    }

    public Register(RegisterId id, User users, Op ops, Date recordTime) {
        this.id = id;
        this.user = users;
        this.op = ops;
        this.recordTime = recordTime;
    }

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "id", column =
                @Column(name = "id", nullable = false)),
        @AttributeOverride(name = "userId", column =
                @Column(name = "user_id", nullable = false)),
        @AttributeOverride(name = "opId", column =
                @Column(name = "op_id", nullable = false))})
    public RegisterId getId() {
        return this.id;
    }

    public void setId(RegisterId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User users) {
        this.user = users;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "op_id", nullable = false, insertable = false, updatable = false)
    public Op getOp() {
        return this.op;
    }

    public void setOp(Op ops) {
        this.op = ops;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "record_time", length = 19)
    public Date getRecordTime() {
        return this.recordTime;
    }

    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }
}
