package hb.tools;
// Generated Nov 15, 2012 8:58:31 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company  implements java.io.Serializable {


     private Integer companyId;
     private String name;
     private Set customers = new HashSet(0);
     private Set suppliers = new HashSet(0);

    public Company() {
    }

	
    public Company(String name) {
        this.name = name;
    }
    public Company(String name, Set customers, Set suppliers) {
       this.name = name;
       this.customers = customers;
       this.suppliers = suppliers;
    }
   
    public Integer getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set customers) {
        this.customers = customers;
    }
    public Set getSuppliers() {
        return this.suppliers;
    }
    
    public void setSuppliers(Set suppliers) {
        this.suppliers = suppliers;
    }




}


