package hb.tools;
// Generated Nov 15, 2012 8:58:31 PM by Hibernate Tools 3.2.1.GA

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

    private Integer customerId;
    private Company company;
    private String name;

    public Customer() {
    }

    public Customer(Company company, String name) {
        this.company = company;
        this.name = name;
    }

    public Integer getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    public Company getCompany() {
        return this.company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
