package hb.tools;
// Generated Nov 15, 2012 8:58:31 PM by Hibernate Tools 3.2.1.GA



/**
 * Supplier generated by hbm2java
 */
public class Supplier  implements java.io.Serializable {


     private Integer supplierId;
     private Company company;
     private String name;

    public Supplier() {
    }

    public Supplier(Company company, String name) {
       this.company = company;
       this.name = name;
    }
   
    public Integer getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


